#ifndef SYSMONITOR_VERSION_H
#define SYSMONITOR_VERSION_H

#define SYSMONITOR_VERSION "2.0.1"
#define SYSMONITOR_VERSION_MAJOR 2
#define SYSMONITOR_VERSION_MINOR 0
#define SYSMONITOR_VERSION_PATCH 1

#endif // SYSMONITOR_VERSION_H