#ifndef SYSMONITOR_VERSION_H
#define SYSMONITOR_VERSION_H

#define SYSMONITOR_VERSION "1.0.1"
#define SYSMONITOR_VERSION_MAJOR 1
#define SYSMONITOR_VERSION_MINOR 0
#define SYSMONITOR_VERSION_PATCH 1

#endif // SYSMONITOR_VERSION_H