name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential
    
    - name: Build
      run: |
        mkdir build && cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release
        make -j$(nproc)
    
    - name: Test
      run: |
        cd build
        ctest --verbose
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: sysmonitor-linux
        path: build/bin/sysmonitor

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    
    - name: Build
      run: |
        mkdir build
        cd build
        cmake .. -G "Visual Studio 16 2019" -A x64
        cmake --build . --config Release
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: sysmonitor-windows
        path: build/bin/Release/sysmonitor.exe

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: brew install cmake
    
    - name: Build
      run: |
        mkdir build && cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release
        make -j$(sysctl -n hw.ncpu)
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: sysmonitor-macos
        path: build/bin/sysmonitor